version: '3.9'
services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: dofus_duo
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data